// src/components/Navbar.vue
<template lang="">
<div class="navbar bg-base-200 px-4">
    <div class="flex-1">
        <RouterLink to="/"><span class="logo text-primary normal-case text-xl">Andrew Shoemaker</span></RouterLink>
    </div>
    <div class="flex-none">
        <ul class="menu menu-horizontal px-1">
        <li><RouterLink to="/">Home</RouterLink></li>
        <li><RouterLink to="/resume">Resume</RouterLink></li>
        </ul>
    </div>
</div>
</template>

<style lang="">
    
</style>

// src/app/layout/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router'

@Component({
  selector: 'app-navbar',
  template: `
    <div class="">
      <div class="navbar bg-base-100">
        <div class="flex-1">
          <a class="normal-case text-2xl" routerLink="/"><span class="fs-4 grad-text"><i class="fa-solid fa-code"></i> Andrew Shoemaker</span></a>
        </div>
        <div class="flex-none">
          <ul class="menu menu-horizontal p-0">
            <li class=""><a [class.grad-text]="hasRoute('/')" routerLink="/" aria-current="page">Home</a></li>
            <li class=""><a [class.grad-text]="hasRoute('/resume')" routerLink="/resume">Resume</a></li>
          </ul>
        </div>
      </div>
      </div>
      `,
  styles: [
  ]
})
export class NavbarComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  hasRoute(route: string) {
    return this.router.url === route;
  }

}
